version: "3.8"

services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app
    command: "pnpm dev" # For local development; change to `start` in production

  postgres:
    image: postgres:15
    container_name: local_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nuxtuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: nuxtdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080" # Expose Adminer on port 8080
    depends_on:
      - postgres # Wait for the postgres container to start before Adminer
    environment:
      - ADMINER_DEFAULT_SERVER=postgres

volumes:
  pgdata:
